server:
  port: 2101

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8500/

#8500是consul访问的默认端口
spring:
  application:
    name: consul-consumer
  cloud:
    consul:
      port: 8500

#defaultZone 指定服务注册中心的位置


