server:
  port: 1001

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#registerWithEureka: false  fetchRegistry: false  是为了防止eureka自己作为客户端注册自己